config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :tracks

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id                  :bigint           not null, primary key
#  age_top10           :integer          default(0), not null
#  album               :string           default("Unknown"), not null
#  album_image_url     :string           default("https://img.freepik.com/free-vector/dark-wavy-shape-with-shinny-light-background_1409-1923.jpg?w=1380"), not null
#  name                :string           default("Song Name"), not null
#  preview_url         :string
#  rank                :integer          default(-1), not null
#  youtube_likes_count :integer          default(0), not null
#  youtube_url         :string           default("https://www.youtube.com/watch?v=u31qwQUeGuM"), not null
#  youtube_views_count :integer          default(0), not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  spotify_id          :string           default(""), not null
#
# Indexes
#
#  index_tracks_on_spotify_id  (spotify_id) UNIQUE
#
class Track < ApplicationRecord
  has_many :artist_tracks
  has_many :artists, through: :artist_tracks, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: %i[ show edit update destroy ]

  # GET /tracks
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to @track, notice: "Track was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tracks/1
  def update
    if @track.update(track_params)
      redirect_to @track, notice: "Track was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tracks/1
  def destroy
    @track.destroy
    redirect_to tracks_url, notice: "Track was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:album, :album_image_url, :spotify_id, :name, :preview_url, :youtube_url, :youtube_likes_count, :youtube_views_count, :rank, :age_top_10)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
  <% if track.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
        <% track.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :album, style: "display: block" %>
    <%= form.text_field :album %>
  </div>

  <div>
    <%= form.label :album_image_url, style: "display: block" %>
    <%= form.text_field :album_image_url %>
  </div>

  <div>
    <%= form.label :spotify_id, style: "display: block" %>
    <%= form.text_field :spotify_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preview_url, style: "display: block" %>
    <%= form.text_field :preview_url %>
  </div>

  <div>
    <%= form.label :youtube_url, style: "display: block" %>
    <%= form.text_field :youtube_url %>
  </div>

  <div>
    <%= form.label :youtube_likes_count, style: "display: block" %>
    <%= form.number_field :youtube_likes_count %>
  </div>

  <div>
    <%= form.label :youtube_views_count, style: "display: block" %>
    <%= form.number_field :youtube_views_count %>
  </div>

  <div>
    <%= form.label :rank, style: "display: block" %>
    <%= form.number_field :rank %>
  </div>

  <div>
    <%= form.label :age_top_10, style: "display: block" %>
    <%= form.number_field :age_top_10 %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tracks/_track.html.erb
<div id="<%= dom_id track %>">
  <p>
    <strong>Album:</strong>
    <%= track.album %>
  </p>

  <p>
    <strong>Album image url:</strong>
    <%= track.album_image_url %>
  </p>

  <p>
    <strong>Spotify:</strong>
    <%= track.spotify_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= track.name %>
  </p>

  <p>
    <strong>Preview url:</strong>
    <%= track.preview_url %>
  </p>

  <p>
    <strong>Youtube url:</strong>
    <%= track.youtube_url %>
  </p>

  <p>
    <strong>Youtube likes count:</strong>
    <%= track.youtube_likes_count %>
  </p>

  <p>
    <strong>Youtube views count:</strong>
    <%= track.youtube_views_count %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= track.rank %>
  </p>

  <p>
    <strong>Age top 10:</strong>
    <%= track.age_top_10 %>
  </p>

</div>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Show this track", @track %> |
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tracks</h1>

<div id="tracks">
  <% @tracks.each do |track| %>
    <%= render track %>
    <p>
      <%= link_to "Show this track", track %>
    </p>
  <% end %>
</div>

<%= link_to "New track", new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render "form", track: @track %>

<br>

<div>
  <%= link_to "Back to tracks", tracks_path %>
</div>

app/views/tracks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @track %>

<div>
  <%= link_to "Edit this track", edit_track_path(@track) %> |
  <%= link_to "Back to tracks", tracks_path %>

  <%= button_to "Destroy this track", @track, method: :delete %>
</div>